sudo: required
language: python
python:
  - "3.6"      
  - "3.7"
  - "3.8"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - make test
  - make image
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make push-image