sudo: required
language: python
os: linux
python:
  - "3.6"      
  - "3.7"
  - "3.8"
services:
  - docker
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: Test and Build Docker Image
      script:
        - make test
        - make type-check
        - make build-image
    - stage: Run Image - Verify Behaviour
      script:
        - make run-image
      script:
        - make run-image
    - stage: Push to Docker Hub
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make push-image