sudo: required
language: python
python: 3.7
os: linux
services:
  - docker
install:
  - pip install -r requirements.txt
stages:
  - test-code
  - test-image
  - deploy
jobs:
  include:
    - stage: test-code
      script:
        - make test
        - make type-check
    - stage: test-image
      script:
        - make build-image
        - make run-image
    - stage: deploy
      if: [ ($TRAVIS_PULL_REQUEST = "false" ) && ( $TRAVIS_BRANCH = "master") ]
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - make build-image
        - make push-image