sudo: required
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - make test
  - docker build --tag travis-ci-exemplar-image .
  - docker run travis-ci-exemplar-image